### ISSUE TITLE
Document code generation approach

### ISSUE THREAD

**Issue by domesticmouse** [devoncarew/analysis_server_lib#47]
The `lib/analysis_server_lib.dart` file contains the warning that this file is code generated. However, I can't see how to regenerate the code nor the template used to generate this file from.

The reason I ask is that I'd like to add error handling to the `create` method. Currently this code dies silently if run from a Flutter app, presumably on a failure to find the Dart SDK.

**Comment by devoncarew** [comment]
AFK right now, but the regeneration script should be in the tool/ dir.

**Comment by domesticmouse** [comment]
Got it. No rush, but I'd appreciate your thoughts on https://github.com/devoncarew/analysis_server_lib/pull/48 when you have a spare moment. Thanks!
